[package]
name = "mcstat"
version = "0.1.0"
authors = ["LordMZTE <lord@mzte.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
asciify = "0.1.6"
clap = "2.33.3"
image = "0.23.14"
image-base64 = "0.1.0"
itertools = "0.10.0"
lazy_static = "1.4.0"
serde_json = "1.0.64"
smart-default = "0.6.0"
structopt = "0.3.21"
term_size = "0.3.2"
termcolor = "1.1.2"
unicode-width = "0.1.8"
yaml-rust = "0.4.5"

[dependencies.async-minecraft-ping]
git = "https://github.com/LordMZTE/async-minecraft-ping.git"
tag = "v0.2.5"

[dependencies.tokio]
version = "1.5.0"
features = ["rt-multi-thread", "macros", "time"]

[build-dependencies]
clap = "2.33.3"
lazy_static = "1.4.0"
yaml-rust = "0.4.5"
