[package]
name = "mcstat"
version = "0.1.0"
authors = ["LordMZTE <lord@mzte.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^2.33", features = ["yaml"] }
image-base64 = "0.1.0"
image = "0.23.9"
asciify = "0.1.6"
async-minecraft-ping = { path="../../../async-minecraft-ping/async-minecraft-ping" }
tokio = { version = "0.2.22", features = ["full"] }
itertools = "0.9.0"
termcolor = "1"
anyhow = "1.0.32"
serde_json = "1.0.58"
