[package]
name = "mcstat"
version = "0.1.0"
authors = ["LordMZTE <lord@mzte.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcio = "0.3.1"
clap = "^2.33"
image-base64 = "0.1.0"
image = "0.23.9"
asciify = "0.1.5"
