[package]
name = "mcstat"
version = "0.1.0"
authors = ["LordMZTE <lord@mzte.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33"
image-base64 = "0.1.0"
image = "0.23.9"
asciify = "0.1.5"
async-minecraft-ping = "0.2.1"
tokio = { version = "0.2.22", features = ["full"] }
itertools = "0.9.0"
